baseURL = "https://gocat.dev/"
languageCode = "ru-ru"
title = "GoCat.dev"

# robots.txt через обработку
enableRobotsTXT = true

[params]
  description = "Документация по Golang на русском языке - Tour of Go, руководства, примеры"

# Для sitemap
[sitemap]
  changefreq = "weekly"
  priority = 0.5

[services]
  [services.googleAnalytics]
    ID = "your-id"